using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class ScriptableObjectClassSample : ScriptableObject {
    public List<Param> list = new List<Param> ();

    [System.SerializableAttribute]
    public class Param
    {
        public int Hp;
        public int Mp;
    
        public long dummy_0;
        public long dummy_1;
        public long dummy_2;
        public long dummy_3;
        public long dummy_4;
        public long dummy_5;
        public long dummy_6;
        public long dummy_7;
        public long dummy_8;
        public long dummy_9;
        public long dummy_10;
        public long dummy_11;
        public long dummy_12;
        public long dummy_13;
        public long dummy_14;
        public long dummy_15;
        public long dummy_16;
        public long dummy_17;
        public long dummy_18;
        public long dummy_19;
        public long dummy_20;
        public long dummy_21;
        public long dummy_22;
        public long dummy_23;
        public long dummy_24;
        public long dummy_25;
        public long dummy_26;
        public long dummy_27;
        public long dummy_28;
        public long dummy_29;
        public long dummy_30;
        public long dummy_31;
        public long dummy_32;
        public long dummy_33;
        public long dummy_34;
        public long dummy_35;
        public long dummy_36;
        public long dummy_37;
        public long dummy_38;
        public long dummy_39;
        public long dummy_40;
        public long dummy_41;
        public long dummy_42;
        public long dummy_43;
        public long dummy_44;
        public long dummy_45;
        public long dummy_46;
        public long dummy_47;
        public long dummy_48;
        public long dummy_49;
        public long dummy_50;
        public long dummy_51;
        public long dummy_52;
        public long dummy_53;
        public long dummy_54;
        public long dummy_55;
        public long dummy_56;
        public long dummy_57;
        public long dummy_58;
        public long dummy_59;
        public long dummy_60;
        public long dummy_61;
        public long dummy_62;
        public long dummy_63;
        public long dummy_64;
        public long dummy_65;
        public long dummy_66;
        public long dummy_67;
        public long dummy_68;
        public long dummy_69;
        public long dummy_70;
        public long dummy_71;
        public long dummy_72;
        public long dummy_73;
        public long dummy_74;
        public long dummy_75;
        public long dummy_76;
        public long dummy_77;
        public long dummy_78;
        public long dummy_79;
        public long dummy_80;
        public long dummy_81;
        public long dummy_82;
        public long dummy_83;
        public long dummy_84;
        public long dummy_85;
        public long dummy_86;
        public long dummy_87;
        public long dummy_88;
        public long dummy_89;
        public long dummy_90;
        public long dummy_91;
        public long dummy_92;
        public long dummy_93;
        public long dummy_94;
        public long dummy_95;
        public long dummy_96;
        public long dummy_97;
        public long dummy_98;
        public long dummy_99;
    }
}

